# Running R from a tgz.
##
Universe   = vanilla
Priority   = 1000

should_transfer_files = Yes
when_to_transfer_output = ON_EXIT_OR_EVICT
transfer_input_files = R-power.tar.gz,nums.csv,in0.r,in1.r,in2.r,in3.r

Executable = runR.bash
Arguments  = in$(Process).r

Log        = Rlog_$(Cluster).txt
Input      = in$(Process).r
Output     = Rout_$(Cluster)_$(Process).txt
Error      = Rerr_$(Cluster)_$(Process).txt
# Solicitar 1 core y 1024M RAM
#request_cpus = 1
#request_memory = 1024
Queue 4

